name: configuration_secrets

on: 
  workflow_dispatch:
  
env:
  cloud: azure-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hey its configuration variable file
    steps: 
      - name: "Say its configuration file"
        run: echo "$Greeting $First_Name is using $cloud with project ${{ vars.PROJECT_ID }}!"
        env:
          First_Name: Rishabh
