name: variable

on: 
  workflow_dispatch:
  
env:
  cloud: azure-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps: 
      - name: "Say Hello Rishi now 4 o'clock"
        run: echo "$Greeting $First_Name is using $cloud!"
        env:
          First_Name: Rishabh
